# Generated by Django 3.0.3 on 2020-03-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('TT', '税收协定'), ('HH', '税费法律'), ('MH', '行政法规'), ('LH', '中央政策'), ('HM', '地方性法规'), ('MM', '司法解释'), ('LM', '部门规章'), ('HL', '地方政府规章'), ('ML', '部委规范性文件'), ('LL', '地方规范性文件'), ('XX', '其他文件')], default='ML', max_length=2, verbose_name='法律层级')),
                ('title', models.CharField(help_text='请输入文件标题', max_length=100, unique=True, verbose_name='法规名称')),
                ('file_order', models.CharField(blank=True, help_text='请输入发文序号', max_length=4, null=True, verbose_name='文件序号')),
                ('reporter', models.CharField(blank=True, help_text='如有，请输入签发人', max_length=40, null=True, verbose_name='签发人')),
                ('pub_date', models.DateField(help_text='请输入文件正式签发日期', verbose_name='签发日期')),
                ('val_date', models.DateField(help_text='请输入文件生效日期', verbose_name='生效日期')),
                ('dis_date', models.DateField(blank=True, help_text='请输入文件失效日期', null=True, verbose_name='失效日期')),
                ('content_less', models.TextField(verbose_name='文头/前言')),
                ('content_tail', models.CharField(blank=True, help_text='说明文件个别条款的特别执行期间等内容', max_length=200, null=True, verbose_name='文末/备注')),
                ('snapshot', models.URLField(help_text='请输入文件官网链接', verbose_name='可打印版本链接')),
                ('att_image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图表等附件')),
            ],
        ),
        migrations.CreateModel(
            name='Fileprefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_prefix', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('prov_order', models.SmallAutoField(help_text='由数据库系统自动生成', primary_key=True, serialize=False, verbose_name='条文序号')),
                ('document', models.ForeignKey(help_text='请选择具体规定条款所属文件', on_delete=django.db.models.deletion.CASCADE, to='lawlib.Document', verbose_name='所属文件')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', '初始有效'), ('F', '修订有效'), ('P', '暂停执行'), ('A', '恢复执行'), ('D', '条款失效'), ('Z', '模糊待定')], default='I', help_text='请选择该条款当前效力状态', max_length=1, verbose_name='生效状态')),
                ('item_attr', models.CharField(choices=[('QYYW', '前言引文'), ('JSFR', '缴税费人'), ('ZSFW', '课征对象'), ('BYZS', '不予征收'), ('ZSPM', '征收品目'), ('SLFL', '税率费率'), ('JSFS', '计算方式'), ('MZYH', '免征优惠'), ('ZMYH', '暂免优惠'), ('SJJZ', '税基减征'), ('SLJZ', '税率减征'), ('SEJZ', '税额减征'), ('SJZJ', '税基暂减'), ('SLZJ', '税率暂减'), ('SEZJ', '税额暂减'), ('KJDM', '跨境抵免'), ('JNFS', '缴纳方式'), ('JNHJ', '缴纳环节'), ('DZDK', '代征代扣'), ('SBQX', '申报期限'), ('JNQX', '缴纳期限'), ('JNDD', '缴纳地点'), ('ZFGL', '总分管理'), ('YZYJ', '预征预缴'), ('HSQJ', '汇算清缴'), ('TDSF', '退抵税费'), ('CKTS', '出口退税'), ('LDTS', '留抵退税'), ('JZJT', '即征即退'), ('XZHF', '先征后返'), ('TBTZ', '特别调整'), ('xkrd', '许可认定'), ('SDFP', '税单发票'), ('YHBL', '优惠办理'), ('XXBG', '信息报告'), ('FWJC', '服务举措'), ('CKCL', '财会处理'), ('XXXT', '信息系统'), ('BMXJ', '部门衔接'), ('XYGL', '信用管理'), ('SWJC', '税务检查'), ('XZQZ', '行政强制'), ('XZCF', '行政处罚'), ('FLJJ', '法律救济'), ('ZCCL', '追责处理'), ('HHLX', '混合类型'), ('LFSQ', '立法授权'), ('ZXRQ', '执行日期'), ('QTGD', '其他规定')], default='qtgd', help_text='请选择条款内容属性', max_length=4, verbose_name='规制内容')),
                ('val_date', models.DateField(default='2019-1-1', verbose_name='条款开始生效期')),
                ('dis_date', models.DateField(blank=True, null=True, verbose_name='条款失效日期')),
                ('content_p1', models.TextField(default='', help_text='如仅有一段，第一段即为条款全部内容，不需要再输入', verbose_name='第一款内容')),
                ('rules', models.ForeignKey(help_text='请选择条款所属法条', on_delete=django.db.models.deletion.CASCADE, to='lawlib.Provision', verbose_name='所属法条')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='fileprefix',
            field=models.ForeignKey(blank=True, help_text='请选择发文代字,如 国发 ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawlib.Fileprefix', verbose_name='发文代字'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ManyToManyField(help_text='请输入发文机关', to='lawlib.Organization', verbose_name='发布机关'),
        ),
        migrations.AddField(
            model_name='document',
            name='revenue',
            field=models.ManyToManyField(help_text='选择税（费）种名称', to='lawlib.Revenue', verbose_name='所涉及税（费）种'),
        ),
    ]
