# Generated by Django 3.0.3 on 2020-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='title',
            field=models.CharField(default='', max_length=10, verbose_name='（显示）条文序号'),
        ),
    ]
