# Generated by Django 3.0.3 on 2020-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0002_provision_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='content_p1',
        ),
        migrations.AddField(
            model_name='rule',
            name='content',
            field=models.TextField(default='', help_text='如仅有一段，第一段即为条款全部内容，不需要再输入', verbose_name='本款内容'),
        ),
    ]
