# Generated by Django 3.0.3 on 2020-03-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0006_auto_20200303_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fileprefix',
            field=models.ForeignKey(blank=True, help_text='请选择发文代字,如未列出，点旁边 ＋号增添 ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawlib.Fileprefix', verbose_name='发文代字'),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ManyToManyField(help_text='请输入发文机关,如未列出，点旁边 ＋号增添', to='lawlib.Organization', verbose_name='发布机关'),
        ),
        migrations.AlterField(
            model_name='document',
            name='revenue',
            field=models.ManyToManyField(help_text='选择税（费）种名称,如未列出，点旁边 ＋号增添', to='lawlib.Revenue', verbose_name='所涉及税（费）种'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content',
            field=models.TextField(default='', help_text='如仅有一段，第一段即为条款全部内容，下面不需要再输入', verbose_name='本款内容'),
        ),
    ]
