# Generated by Django 3.0.3 on 2020-03-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0007_auto_20200303_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='prov_order',
            field=models.AutoField(help_text='由数据库系统自动生成', primary_key=True, serialize=False, verbose_name='存储主键'),
        ),
    ]
