# Generated by Django 3.0.3 on 2020-03-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0008_auto_20200303_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_order',
            field=models.CharField(blank=True, help_text='请输入发文序号', max_length=9, null=True, verbose_name='文件序号'),
        ),
    ]
