# Generated by Django 3.0.3 on 2020-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0009_auto_20200303_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='title',
            field=models.CharField(default='', max_length=10, verbose_name='条文序号'),
        ),
    ]
