# Generated by Django 3.0.3 on 2020-03-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0011_auto_20200303_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['pub_date'], 'verbose_name': '文件'},
        ),
        migrations.AlterModelOptions(
            name='fileprefix',
            options={'verbose_name': '发文代字'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '发文机关'},
        ),
        migrations.AlterModelOptions(
            name='provision',
            options={'ordering': ['prov_order'], 'verbose_name': '条'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': '税费名称'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '款'},
        ),
    ]
