# Generated by Django 3.0.3 on 2020-03-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0012_auto_20200303_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['pub_date'], 'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterModelOptions(
            name='fileprefix',
            options={'verbose_name': '发文代字', 'verbose_name_plural': '发文代字'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '发文机关', 'verbose_name_plural': '发文机关'},
        ),
        migrations.AlterModelOptions(
            name='provision',
            options={'ordering': ['prov_order'], 'verbose_name': '条(款)', 'verbose_name_plural': '条(款)'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': '税费名称', 'verbose_name_plural': '税费名称'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '款', 'verbose_name_plural': '款'},
        ),
    ]
