# Generated by Django 3.0.3 on 2020-03-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0013_auto_20200303_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_tail',
            field=models.CharField(blank=True, help_text='说明文件个别条款的特别执行期间等内容', max_length=500, null=True, verbose_name='文末/备注'),
        ),
    ]
