# Generated by Django 3.0.3 on 2020-03-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0014_auto_20200304_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_tail',
            field=models.TextField(blank=True, help_text='说明文件个别条款的特别执行期间等内容', null=True, verbose_name='文末/备注'),
        ),
    ]
