# Generated by Django 3.0.3 on 2020-03-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0016_auto_20200304_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_less',
            field=models.TextField(blank=True, help_text='（可选）不在此处输入条款具体规定内容', null=True, verbose_name='文头/前言'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_tail',
            field=models.TextField(blank=True, help_text='(可选)输入一些强调性要求，个别特殊事项说明等内容', null=True, verbose_name='文末/备注'),
        ),
        migrations.AlterField(
            model_name='document',
            name='snapshot',
            field=models.URLField(help_text='请输入文件官网链接,如为财政部文件，链接指向财政部发布该文件的网址;如为中共中央文件,输入国务院网站链接;找不到官网链接，输入本网站网址 http://taxagent.top 暂时代替', verbose_name='官网文件链接'),
        ),
    ]
