# Generated by Django 3.0.3 on 2020-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0017_auto_20200304_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='status',
            field=models.CharField(choices=[('G', '政府部门'), ('M', '市场主体'), ('F', '混合类型')], default='M', help_text='请选择该条需何方履行义务', max_length=1, verbose_name='义务归属方'),
        ),
    ]
