# Generated by Django 3.0.3 on 2020-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0019_auto_20200306_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='duty',
            field=models.CharField(choices=[('G', '政府部门'), ('M', '市场主体'), ('F', '混合类型')], default='M', help_text='请选择该条需何方履行义务', max_length=1, verbose_name='义务归属方'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='status',
            field=models.CharField(choices=[('I', '初始有效'), ('F', '修订有效'), ('P', '暂停执行'), ('A', '恢复执行'), ('D', '条款失效'), ('Z', '模糊待定')], default='I', help_text='请选择该条款当前效力状态', max_length=1, verbose_name='生效状态'),
        ),
    ]
