# Generated by Django 3.0.3 on 2020-03-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0024_document_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_less',
            field=models.TextField(blank=True, help_text='（可选）不在此处输入条款具体规定内容', null=True, verbose_name='目录/前言'),
        ),
    ]
