# Generated by Django 3.0.3 on 2020-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0026_taxreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreturn',
            name='base_file',
            field=models.CharField(default='税务总局关于**公告（税务总局公告20xx第x号）', help_text='请修改为正确的明确该申报表样式、使用日期等启用事项的文件名称', max_length=100, verbose_name='启用申报表文件'),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='fill_form',
            field=models.TextField(help_text='请粘贴申报表HTML代码，可用wps-office可从doc/xls等文档转存得到', verbose_name='表格内容'),
        ),
    ]
