# Generated by Django 3.0.3 on 2020-03-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0027_auto_20200307_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxreturn',
            old_name='tilte',
            new_name='title',
        ),
    ]
