# Generated by Django 3.0.3 on 2020-03-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawlib', '0028_auto_20200308_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreturn',
            name='dis_date',
            field=models.DateField(blank=True, help_text='输入该版本申报表从税款属期最迟哪天不可用', null=True, verbose_name='停用日期'),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='val_date',
            field=models.DateField(default='2019-1-1', help_text='输入该版本申报表从税款属期最早哪天可用', verbose_name='启用日期'),
        ),
    ]
